
// This file has been generated by the GUI designer. Do not modify.
namespace StatDisk
{
	public partial class StatsWindow
	{
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label5;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.Label label6;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox12;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TextView visorTiempos;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.TextView visorTiempos1;
		private global::Gtk.HBox hbox13;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.TextView visorCalculos;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.ScrolledWindow scrolledwindow4;
		private global::Gtk.TextView visorCalculos1;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget StatDisk.StatsWindow
			this.Name = "StatDisk.StatsWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Internal child StatDisk.StatsWindow.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Medio de almacenamiento A");
			this.hbox14.Add (this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label5]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox14.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vseparator4]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Medio de almacenamiento B");
			this.hbox14.Add (this.label6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label6]));
			w4.Position = 2;
			w1.Add (this.hbox14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox14]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.visorTiempos = new global::Gtk.TextView ();
			this.visorTiempos.CanFocus = true;
			this.visorTiempos.Name = "visorTiempos";
			this.visorTiempos.Editable = false;
			this.visorTiempos.CursorVisible = false;
			this.scrolledwindow1.Add (this.visorTiempos);
			this.hbox12.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.scrolledwindow1]));
			w7.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox12.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vseparator2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.visorTiempos1 = new global::Gtk.TextView ();
			this.visorTiempos1.CanFocus = true;
			this.visorTiempos1.Name = "visorTiempos1";
			this.visorTiempos1.Editable = false;
			this.visorTiempos1.CursorVisible = false;
			this.scrolledwindow2.Add (this.visorTiempos1);
			this.hbox12.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.scrolledwindow2]));
			w10.Position = 2;
			this.vbox5.Add (this.hbox12);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox12]));
			w11.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.visorCalculos = new global::Gtk.TextView ();
			this.visorCalculos.CanFocus = true;
			this.visorCalculos.Name = "visorCalculos";
			this.visorCalculos.Editable = false;
			this.visorCalculos.CursorVisible = false;
			this.scrolledwindow3.Add (this.visorCalculos);
			this.hbox13.Add (this.scrolledwindow3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.scrolledwindow3]));
			w13.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox13.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vseparator3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.visorCalculos1 = new global::Gtk.TextView ();
			this.visorCalculos1.CanFocus = true;
			this.visorCalculos1.Name = "visorCalculos1";
			this.visorCalculos1.Editable = false;
			this.visorCalculos1.CursorVisible = false;
			this.scrolledwindow4.Add (this.visorCalculos1);
			this.hbox13.Add (this.scrolledwindow4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.scrolledwindow4]));
			w16.Position = 2;
			this.vbox5.Add (this.hbox13);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox13]));
			w17.Position = 1;
			w1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox5]));
			w18.Position = 1;
			// Internal child StatDisk.StatsWindow.ActionArea
			global::Gtk.HButtonBox w19 = this.ActionArea;
			w19.Name = "dialog1_ActionArea";
			w19.Spacing = 10;
			w19.BorderWidth = ((uint)(5));
			w19.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-quit";
			this.AddActionWidget (this.buttonOk, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w19 [this.buttonOk]));
			w20.Expand = false;
			w20.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
